cifsd: Select SG_POOL for SMB_SERVER
hulk-robot following build error:
 fs/cifsd/transport_rdma.c: In function ‘read_write_done’:
 fs/cifsd/transport_rdma.c:1297:2: error: implicit declaration of function ‘sg_free_table_chained’ [-Werror=implicit-function-declaration]
  1297 |  sg_free_table_chained(&msg->sgt, SG_CHUNK_SIZE);

The reason is CONFIG_SG_POOL is not enabled in the config, to
avoid such failure, select SG_POOL in Kconfig for SMB_SERVER.

Fixes: 75b8988dfe83 ("cifsd: add server handler for central processing and tranport layers")
Signed-off-by: Zhang Xiaoxu <zhangxiaoxu5@huawei.com>