fix multiple definition linking error due to missing extern
GCC 10+ defaults to -fno-common, which enforces proper declaration of
external references using "extern". without this change a link would
fail with:

  ld: raid6.a(algos.o):lib/raid6/test/algos.c:28: multiple definition of `raid6_call';
                       lib/raid6/test/test.c:22: first defined here

Signed-off-by: Dirk Müller <dmueller@suse.de>