futex: Fix sparc32/m68k/nds32 build regression
In one of the revisions of my futex cleanup series, I botched
up a rename of some function names, breaking sparc32, m68k
and nds32:

include/asm-generic/futex.h:17:2: error: implicit declaration of function 'futex_atomic_cmpxchg_inatomic_local_generic'; did you mean 'futex_atomic_cmpxchg_inatomic_local'? [-Werror=implicit-function-declaration]

Fix the macros to point to the correct functions.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Fixes: 3f2bedabb62c ("futex: Ensure futex_atomic_cmpxchg_inatomic() is present")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>