libbpf: Modify bpf_printk to choose helper based on arg count
Instead of being a thin wrapper which calls into bpf_trace_printk,
libbpf's bpf_printk convenience macro now chooses between
bpf_trace_printk and bpf_trace_vprintk. If the arg count (excluding
format string) is >3, use bpf_trace_vprintk, otherwise use the older
helper.

The motivation behind this added complexity - instead of migrating
entirely to bpf_trace_vprintk - is to maintain good developer experience
for users compiling against new libbpf but running on older kernels.
Users who are passing <=3 args to bpf_printk will see no change in their
bytecode.

__bpf_vprintk functions similarly to BPF_SEQ_PRINTF and BPF_SNPRINTF
macros elsewhere in the file - it allows use of bpf_trace_vprintk
without manual conversion of varargs to u64 array. Previous
implementation of bpf_printk macro is moved to __bpf_printk for use by
the new implementation.

This does change behavior of bpf_printk calls with >3 args in the "new
libbpf, old kernels" scenario. On my system, using a clang built from
recent upstream sources (14.0.0 https://github.com/llvm/llvm-project.git
50b62731452cb83979bbf3c06e828d26a4698dca), attempting to use 4 args to
__bpf_printk (old impl) results in a compile-time error:

  progs/trace_printk.c:21:21: error: too many args to 0x6cdf4b8: i64 = Constant<6>
        trace_printk_ret = __bpf_printk("testing,testing %d %d %d %d\n",

I was able to replicate this behavior with an older clang as well. When
the format string has >3 format specifiers, there is no output to the
trace_pipe in either case.

After this patch, using bpf_printk with 4 args would result in a
trace_vprintk helper call being emitted and a load-time failure on older
kernels.

Signed-off-by: Dave Marchevsky <davemarchevsky@fb.com>