atm: firestream: avoid conversion error during build
Although the firestream driver isn't relevant for the parisc
architecture, but it generates this compile error when CONFIG_TEST is
defined:

 drivers/atm/firestream.c: In function ‘top_off_fp’:
 arch/parisc/include/asm/io.h:8:25: error: conversion from ‘long unsigned int’ to ‘u32’ {aka ‘unsigned int’} changes value
     from ‘18446744072635809792’ to ‘3221225472’ [-Werror=overflow]
 drivers/atm/firestream.c:1494:29: note: in expansion of macro ‘virt_to_bus’
            ne->next  = virt_to_bus (NULL);

ne->next is of type u32, so this patch avoids the error by casting
the return value of virt_to_bus() to u32.

Signed-off-by: Helge Deller <deller@gmx.de>