jbd2: fix jbd2_journal_[un]register_shrinker undefined error
Export jbd2_journal_unregister_shrinker() and
jbd2_journal_register_shrinker() to fix below error:

 ERROR: modpost: "jbd2_journal_unregister_shrinker" undefined!
 ERROR: modpost: "jbd2_journal_register_shrinker" undefined!

Fixes: 4ba3fcdde7e3 ("jbd2,ext4: add a shrinker to release checkpointed buffers")
Signed-off-by: Zhang Yi <yi.zhang@huawei.com>