ALSA: core: remove initialise static variables to 0
Initializing the static variable to 0 causes the following error
when exec checkpatch:

ERROR: do not initialise statics to 0
FILE: sound/sound_core.c:142:
static int preclaim_oss = 0;

Static variable does not need to be initialised to 0, because
compiler will initialise all uninitialised statics to 0. Thus,
remove the unneeded initializations.

Signed-off-by: Meng Tang <tangmeng@uniontech.com>