HID: intel-ish-hid: hid-client: Fix build error
drivers/hid/intel-ish-hid/ishtp-hid-client.c:956:4: error: initializer element is not constant
  { hid_ishtp_guid },
    ^~~~~~~~~~~~~~

The reason is that we are using non-const expressions to initialize the
static structure, which will probably trigger a compiling error/warning
on gcc-7.5.0. Fix it by converting const variable into macro.

Fixes: 0d0cccc0fd83 ("HID: intel-ish-hid: hid-client: only load for matching devices")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>