net: fungible: fix multiple build problems
It is currently possible to have CONFIG_FUN_ETH=y and CONFIG_TLS=m.
This causes build errors. Therefore FUN_ETH should
	depend on TLS || TLS=n

TLS_DEVICE is a bool symbol, so there is no need to test it as
	depends on TLS && TLS_DEVICE || TLS_DEVICE=n

And due to rules of precedence, the above means
	depends on (TLS && TLS_DEVICE) || TLS_DEVICE=n
but that's probably not what was meant here. More likely it
should have been
	depends on TLS && (TLS_DEVICE || TLS_DEVICE=n)

That no longer matters.

Also, gcc 7.5 does not handle the "C language" vs. #ifdef preprocessor
usage of IS_ENABLED() very well -- it is causing compile errors.

$ gcc --version
gcc (SUSE Linux) 7.5.0

And then funeth uses sbitmap, so it should select SBITMAP in order
to prevent build errors.

Fixes these build errors:

../drivers/net/ethernet/fungible/funeth/funeth_tx.c: In function ‘write_pkt_desc’:
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:244:13: error: implicit declaration of function ‘tls_driver_ctx’ [-Werror=implicit-function-declaration]
   tls_ctx = tls_driver_ctx(skb->sk, TLS_OFFLOAD_CTX_DIR_TX);
             ^~~~~~~~~~~~~~
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:244:37: error: ‘TLS_OFFLOAD_CTX_DIR_TX’ undeclared (first use in this function); did you mean ‘BPF_OFFLOAD_MAP_FREE’?
   tls_ctx = tls_driver_ctx(skb->sk, TLS_OFFLOAD_CTX_DIR_TX);
                                     ^~~~~~~~~~~~~~~~~~~~~~
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:244:37: note: each undeclared identifier is reported only once for each function it appears in
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:245:23: error: dereferencing pointer to incomplete type ‘struct fun_ktls_tx_ctx’
   tls->tlsid = tls_ctx->tlsid;
                       ^~
../drivers/net/ethernet/fungible/funeth/funeth_tx.c: In function ‘fun_start_xmit’:
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:310:6: error: implicit declaration of function ‘tls_is_sk_tx_device_offloaded’ [-Werror=implicit-function-declaration]
      tls_is_sk_tx_device_offloaded(skb->sk)) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:311:9: error: implicit declaration of function ‘fun_tls_tx’; did you mean ‘fun_xdp_tx’? [-Werror=implicit-function-declaration]
   skb = fun_tls_tx(skb, q, &tls_len);
         ^~~~~~~~~~
../drivers/net/ethernet/fungible/funeth/funeth_tx.c:311:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   skb = fun_tls_tx(skb, q, &tls_len);
       ^

and

ERROR: modpost: "__sbitmap_queue_get" [drivers/net/ethernet/fungible/funcore/funcore.ko] undefined!
ERROR: modpost: "sbitmap_finish_wait" [drivers/net/ethernet/fungible/funcore/funcore.ko] undefined!
ERROR: modpost: "sbitmap_queue_clear" [drivers/net/ethernet/fungible/funcore/funcore.ko] undefined!
ERROR: modpost: "sbitmap_prepare_to_wait" [drivers/net/ethernet/fungible/funcore/funcore.ko] undefined!
ERROR: modpost: "sbitmap_queue_init_node" [drivers/net/ethernet/fungible/funcore/funcore.ko] undefined!
ERROR: modpost: "sbitmap_queue_wake_all" [drivers/net/ethernet/fungible/funcore/funcore.ko] undefined!

#Fixes: not-merged-yet ("X")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Dimitris Michailidis <dmichail@fungible.com>
Cc: "David S. Miller" <davem@davemloft.net>
Cc: Jakub Kicinski <kuba@kernel.org>