scsi: core: ufs-pci: hide unused ufshcd_pci_restore function
When CONFIG_PM_SLEEP is disabled, ufshcd_pci_restore() fails
to compile but is also unused:

drivers/scsi/ufs/ufshcd-pci.c: In function 'ufshcd_pci_restore':
drivers/scsi/ufs/ufshcd-pci.c:459:16: error: implicit declaration of function 'ufshcd_system_resume'; did you mean 'ufshcd_runtime_resume'? [-Werror=implicit-function-declaration]
  459 |         return ufshcd_system_resume(dev);
      |                ^~~~~~~~~~~~~~~~~~~~
      |                ufshcd_runtime_resume
At top level:
drivers/scsi/ufs/ufshcd-pci.c:452:12: error: 'ufshcd_pci_restore' defined but not used [-Werror=unused-function]
  452 | static int ufshcd_pci_restore(struct device *dev)
      |            ^~~~~~~~~~~~~~~~~~

Enclose it within the same #ifdef as the related code.

Fixes: 21431d5bdf15 ("scsi: core: ufs-pci: Force a full restore after suspend-to-disk")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>