PCI: apple: select CONFIG_PCI_HOST_COMMON
If this symbol is not already selected by another driver, pci-apple.o
fails to link:

aarch64-linux-ld: drivers/pci/controller/pcie-apple.o: in function `apple_pcie_probe':
pcie-apple.c:(.text+0xd28): undefined reference to `pci_host_common_probe'

Add another 'select' statement here, the same that is used for the
other drivers.

Fixes: a8bbe0366a3e ("PCI: apple: Add initial hardware bring-up")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>