media: atomisp: fix compilation error
I am getting the following compilation error on ubuntu 20.04 with gcc 9.3.0.

drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.c: In function ‘input_system_configure_channel_sensor’:
drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.c:1649:1: error: control reaches end of non-void function [-Werror=return-type]
 1649 | }
      | ^
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:277: drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.o] Error 1

I made some minor changes to the switch-case to keep gcc happy.

Signed-off-by: Tong Zhang <ztong0001@gmail.com>