drm/msm: some features need to be forced to rely on COMMON_CLK
In fact, this will not cause any problems, but when COMPILE_TEST is
enabled, COMMON_CLK may not be selected, The CI system will report
some compilation errors. even if that is not issue, but we better fix
him.

[...]
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_28nm.o: in function `pll_28nm_register':
dsi_phy_28nm.c:(.text+0x868): undefined reference to `devm_clk_hw_register'
x86_64-linux-gnu-ld: dsi_phy_28nm.c:(.text+0x90c): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_28nm.c:(.text+0x979): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_28nm.c:(.text+0x9f8): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_28nm.c:(.text+0xab5): undefined reference to `__devm_clk_hw_register_mux'
x86_64-linux-gnu-ld: dsi_phy_28nm.c:(.text+0xb1e): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_28nm.o: in function `dsi_28nm_pll_save_state':
dsi_phy_28nm.c:(.text+0x1234): undefined reference to `clk_hw_get_rate'
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_28nm_8960.o: in function `dsi_28nm_pll_save_state':
dsi_phy_28nm_8960.c:(.text+0x408): undefined reference to `clk_hw_get_rate'
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_28nm_8960.o: in function `clk_bytediv_round_rate':
dsi_phy_28nm_8960.c:(.text+0x483): undefined reference to `clk_hw_get_parent'
x86_64-linux-gnu-ld: dsi_phy_28nm_8960.c:(.text+0x48e): undefined reference to `clk_hw_round_rate'
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_28nm_8960.o: in function `pll_28nm_register':
dsi_phy_28nm_8960.c:(.text+0x681): undefined reference to `devm_clk_hw_register'
x86_64-linux-gnu-ld: dsi_phy_28nm_8960.c:(.text+0x735): undefined reference to `devm_clk_hw_register'
x86_64-linux-gnu-ld: dsi_phy_28nm_8960.c:(.text+0x796): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_10nm.o: in function `pll_10nm_register':
dsi_phy_10nm.c:(.text+0x705): undefined reference to `devm_clk_hw_register'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0x7b0): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0x83a): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0x8ad): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0x91d): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0x989): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0xaa4): undefined reference to `__devm_clk_hw_register_mux'
x86_64-linux-gnu-ld: dsi_phy_10nm.c:(.text+0xb2a): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: drivers/gpu/drm/msm/dsi/phy/dsi_phy_7nm.o: in function `pll_7nm_register':
dsi_phy_7nm.c:(.text+0xa45): undefined reference to `devm_clk_hw_register'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xaf0): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xb7a): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xbfd): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xc6d): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xcea): undefined reference to `devm_clk_hw_register_fixed_factor'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xda0): undefined reference to `__devm_clk_hw_register_divider'
x86_64-linux-gnu-ld: dsi_phy_7nm.c:(.text+0xed9): undefined reference to `__devm_clk_hw_register_mux'
[...]

Fixes: b3ed524f84f5 ("drm/msm: allow compile_test on !ARM")
Reported-by: kernelbot <kernel-bot@kylinos.cn>
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>