perf tools: Fix build with libpfm
It missed to update the parse_libpfm_events_option() to use a new
helper function to set the event group leader.

  $ make LIBPFM4=1
  ...
    CC      util/pfm.o
  util/pfm.c: In function ‘parse_libpfm_events_option’:
  util/pfm.c:103:9: error: ‘struct evsel’ has no member named ‘leader’
    103 |    evsel->leader = grp_leader;
        |         ^~
  make[4]: *** [tools/build/Makefile.build:96: util/pfm.o] Error 1

Fixes: fba7c86601e2 ("libperf: Move 'leader' from tools/perf to perf_evsel::leader")
Signed-off-by: Namhyung Kim <namhyung@kernel.org>