gpio/rockchip: fix Kconfig to prevent build errors
GPIO_ROCKCHIP needs to enable GENERIC_IRQ_CHIP to prevent build errors.

Eliminates these build errors:
ld: drivers/gpio/gpio-rockchip.o: in function `rockchip_irq_disable':
gpio-rockchip.c:(.text+0x6c9): undefined reference to `irq_gc_mask_set_bit'
ld: drivers/gpio/gpio-rockchip.o: in function `rockchip_irq_enable':
gpio-rockchip.c:(.text+0x709): undefined reference to `irq_gc_mask_clr_bit'
ld: drivers/gpio/gpio-rockchip.o: in function `rockchip_gpio_probe':
gpio-rockchip.c:(.text+0xe25): undefined reference to `irq_generic_chip_ops'
ld: gpio-rockchip.c:(.text+0xe7e): undefined reference to `__irq_alloc_domain_generic_chips'
ld: gpio-rockchip.c:(.text+0xeb9): undefined reference to `irq_get_domain_generic_chip'
ld: gpio-rockchip.c:(.text+0xf04): undefined reference to `irq_gc_ack_set_bit'
ld: gpio-rockchip.c:(.text+0xf0e): undefined reference to `irq_gc_mask_set_bit'
ld: gpio-rockchip.c:(.text+0xf18): undefined reference to `irq_gc_mask_clr_bit'
ld: gpio-rockchip.c:(.text+0xf36): undefined reference to `irq_gc_set_wake'

Fixes: 936ee2675eee ("gpio/rockchip: add driver for rockchip gpio")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Jianqun Xu <jay.xu@rock-chips.com>
Cc: Linus Walleij <linus.walleij@linaro.org>
Cc: Bartosz Golaszewski <brgl@bgdev.pl>
Cc: linux-gpio@vger.kernel.org