ARM: s3c/jive: add one more "fallthrough" statement
clang warns about one missing fallthrough that gcc ignores:

arch/arm/mach-s3c/mach-jive.c:250:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

Add it here as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>