mm/damon: fix stringop-overread warning in kunit test
gcc-11 points out that strnlen() with a fixed length on a constant
input makes no sense:

In file included from mm/damon/dbgfs.c:623:
mm/damon/dbgfs-test.h: In function 'damon_dbgfs_test_str_to_target_ids':
mm/damon/dbgfs-test.h:23:47: error: 'strnlen' specified bound 128 exceeds source size 4 [-Werror=stringop-overread]
   23 |         answers = str_to_target_ids(question, strnlen(question, 128),
      |                                               ^~~~~~~~~~~~~~~~~~~~~~
mm/damon/dbgfs-test.h:30:47: error: 'strnlen' specified bound 128 exceeds source size 7 [-Werror=stringop-overread]
   30 |         answers = str_to_target_ids(question, strnlen(question, 128),
      |                                               ^~~~~~~~~~~~~~~~~~~~~~
mm/damon/dbgfs-test.h:37:47: error: 'strnlen' specified bound 128 exceeds source size 5 [-Werror=stringop-overread]
   37 |         answers = str_to_target_ids(question, strnlen(question, 128),
      |                                               ^~~~~~~~~~~~~~~~~~~~~~

Use a plain strlen() instead.

Fixes: 17ccae8bb5c9 ("mm/damon: add kunit tests")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>