of: fix of_address_to_resource and of_iomap undefined
If CONFIG_OF is selected, but CONFIG_OF_ADDRESS is not, when compiling
files (sunch as timer_of.c) in which the function of_iomap() is invoked,
compiler would report 'undefined reference to of_iomap', the same case
is for of_address_to_resource().

This patch also makes sure that of_iomap() and of_address_to_resource()
are declared for sparc so that sparc can have its specific
implementations in arch/sparc/kernel/of_device_common.c, even if
including include/linux/of_address.h in it.

Signed-off-by: Chunyan Zhang <chunyan.zhang@unisoc.com>