platform/x86: lg-laptop: Fix possible NULL pointer derefence
When CONFIG_DMI is disabled, dmi_get_system_info() returns a NULL
pointer, which is now caught by a warning:

In function 'strlen',
    inlined from 'acpi_add.part.0' at drivers/platform/x86/lg-laptop.c:658:6:
include/linux/fortify-string.h:25:33: error: argument 1 null where non-null expected [-Werror=nonnull]
   25 | #define __underlying_strlen     __builtin_strlen
      |                                 ^
include/linux/fortify-string.h:60:24: note: in expansion of macro '__underlying_strlen'
   60 |                 return __underlying_strlen(p);
      |                        ^~~~~~~~~~~~~~~~~~~
drivers/platform/x86/lg-laptop.c: In function 'acpi_add.part.0':
include/linux/fortify-string.h:25:33: note: in a call to built-in function '__builtin_strlen'
   25 | #define __underlying_strlen     __builtin_strlen
      |                                 ^
include/linux/fortify-string.h:60:24: note: in expansion of macro '__underlying_strlen'
   60 |                 return __underlying_strlen(p);
      |                        ^~~~~~~~~~~~~~~~~~~

The code in there does not appear essential, so an explicit
NULL check should be sufficient. The string is also printed
to the console, but printk() is able to handle NULL pointer
arguments gracefully.

Fixes: 8983bfd58d61 ("platform/x86: lg-laptop: Support for battery charge limit on newer models")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>