media: atmel: atmel-isc: fix build failures after split
When the two isc driver front-ends are both enabled, but one of them
is built-in and the other one is a loadable module, the 'base' driver
is in a state that does not really work, as it would have to be
built in two different ways:

arm-linux-gnueabi-ld: drivers/media/platform/atmel/atmel-isc-base.o: in function `isc_async_complete':
atmel-isc-base.c:(.text+0x1e80): undefined reference to `__this_module'
arm-linux-gnueabi-ld: drivers/media/platform/atmel/atmel-isc-base.o:(.rodata+0x3c8): undefined reference to `__this_module'
arm-linux-gnueabi-ld: drivers/media/platform/atmel/atmel-isc-base.o:(__param+0x4): undefined reference to `__this_module'
arm-linux-gnueabi-ld: drivers/media/platform/atmel/atmel-isc-base.o:(__param+0x18): undefined reference to `__this_module'

As a workaround, turn the base portion of the driver into a library
by itself that can become a standalone module rather than being built
into the two drivers.

Fixes: 0a0e265515db ("media: atmel: atmel-isc: split driver into driver base and isc")
Fixes: c9aa973884a1 ("media: atmel: atmel-isc: add microchip-xisc driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>