OF: of_address: clean up OF stub & extern functions
Adjust <linux/of_address.h> so that stubs are present when
CONFIG_OF is not set *or* OF is set but OF_ADDRESS is not set.

This eliminates 2 build errors on arch/s390/ when HAS_IOMEM
is not set (so OF_ADDRESS is not set).
I.e., it provides a stub for of_iomap() when one was previously
not provided as well as removing some duplicate externs.

s390-linux-ld: drivers/irqchip/irq-al-fic.o: in function `al_fic_init_dt':
irq-al-fic.c:(.init.text+0x7a): undefined reference to `of_iomap'
s390-linux-ld: drivers/clocksource/timer-of.o: in function `timer_of_init':
timer-of.c:(.init.text+0xa4): undefined reference to `of_iomap'

Tested with many randconfig builds, but there could still be some
hidden problem here.

Fixes: 4acf4b9cd453 ("of: move of_address_to_resource and of_iomap declarations from sparc")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Rob Herring <robh+dt@kernel.org>
Cc: Frank Rowand <frowand.list@gmail.com>
Cc: devicetree@vger.kernel.org
Cc: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Reported-by: kernel test robot <lkp@intel.com>