treewide: Remove unnamed static initializations to 0
GCC 4.9 does not like having struct assignments to 0 when members may be
compound types. For example, there are 186 instances of these kinds of
errors:

drivers/virtio/virtio_vdpa.c:146:9: error: missing braces around initializer [-Werror=missing-braces ]
drivers/cxl/core/regs.c:40:17: error: missing braces around initializer [-Werror=missing-braces]

Since "= { 0 }" and "= { }" have the same meaning ("incomplete
initializer") they will both initialize the given variable to zero
(modulo padding games).

After this change, I can almost build the "allmodconfig" target with
GCC 4.9 again.

Signed-off-by: Kees Cook <keescook@chromium.org>