crypto: api - Export crypto_boot_test_finished
Stephen Rothwell <sfr@canb.auug.org.au> wrote:
> [-- text/plain, encoding quoted-printable, charset: US-ASCII, 18 lines --]
>
> Hi all,
>
> After merging the crypto tree, today's linux-next build (powerpc
> ppc44x_defconfig) failed like this:
>
> ERROR: modpost: "crypto_boot_test_finished" [crypto/crypto_algapi.ko] undefined!
>
> Caused by commit
>
>  adad556efcdd ("crypto: api - Fix built-in testing dependency failures")
>
> I have reverted that commit for today.

Oops, does this patch fix the problem?

---8<---
We need to export crypto_boot_test_finished in case api.c is
built-in while algapi.c is built as a module.

Fixes: adad556efcdd ("crypto: api - Fix built-in testing dependency failures")
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>