kconfig: forbid symbols that end with '_MODULE'
Kconfig (syncconfig) generates include/generated/autoconf.h to make
CONFIG options available to the pre-processor.

The macros are suffixed with '_MODULE' for symbols with the value 'm'.

Here is a conflict; CONFIG_FOO=m results in '#define CONFIG_FOO_MODULE 1',
but CONFIG_FOO_MODULE=y also results in the same define.

fixdep always assumes CONFIG_FOO_MODULE comes from CONFIG_FOO=m, so the
dependency is not properly tracked for symbols that end with '_MODULE'.

This commit makes Kconfig error out if it finds a symbol suffixed with
'_MODULE'. This restriction does not exist if the module feature is not
supported (at least from the Kconfig perspective).

It detected one error:
  error: SND_SOC_DM365_VOICE_CODEC_MODULE: symbol name must not end with '_MODULE'

Rename it to SND_SOC_DM365_VOICE_CODEC_MODULAR. Commit 147162f57515
("ASoC: ti: fix SND_SOC_DM365_VOICE_CODEC dependencies") added it for
internal use. So, this renaming has no impact on users.

Remove a comment from drivers/net/wireless/intel/iwlwifi/Kconfig since
this is a hard error now.

Add a comment to include/linux/kconfig.h in order not to worry observant
developers.

Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>