media: staging: media: atomisp: pci: reposition braces as per coding style
This is an automatic generated email to let you know that the following patch were queued:

Subject: media: staging: media: atomisp: pci: reposition braces as per coding style
Author:  Deepak R Varma <drv@mailo.com>
Date:    Fri Apr 30 17:40:12 2021 +0200

Misplaced braces makes it difficult to follow the code easily. This also
goes against the code style guidelines. This resolved following checkpatch
complaints:

ERROR: open brace '{' following function definitions go on the next line
ERROR: that open brace { should be on the previous line

Link: https://lore.kernel.org/linux-media/YIwk3KbVGRPJwKa4@dU2104

[mchehab: dropped a hunk with a merge conflict]
Cc: linux-media@vger.kernel.org, devel@driverdev.osuosl.org, linux-kernel@vger.kernel.org, drv@mailo.com # X-LSpam-Score: -7.3 (-------)
Signed-off-by: Deepak R Varma <drv@mailo.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>

 drivers/staging/media/atomisp/pci/sh_css_mipi.c    |  69 ++++-----
 drivers/staging/media/atomisp/pci/sh_css_params.c  | 171 +++++++++------------
 drivers/staging/media/atomisp/pci/sh_css_sp.c      | 108 ++++++-------
 drivers/staging/media/atomisp/pci/sh_css_version.c |   3 +-
 4 files changed, 155 insertions(+), 196 deletions(-)