cpufreq: qcom-cpufreq-hw: Fix 'make allmodconfig' build
Commit 86afc1df661a adds a reference to a symbol that doesn't have an
EXPORT_SYMBOL, which fails if qcom-cpufreq-hw is built as a module.

ERROR: modpost: "topology_set_thermal_pressure" [drivers/cpufreq/qcom-cpufreq-hw.ko] undefined!

Add the missing EXPORT_SYMBOL.

Fixes: 86afc1df661a ("cpufreq: qcom-cpufreq-hw: Add dcvs interrupt support")
Signed-off-by: Valdis Kletnieks <valdis.kletnieks@vt.edu>