ASoC: mediatek: SND_SOC_MT8195 remove depends on COMPILE_TEST
After compiling with COMPILE_TEST, we are most likely to compile on a
different architecture, such as x86. At this time, it is possible that
the HAVE_CLK macro is not selected, resulting in compilation failure.

Avoid fail like:

  Kernel: arch/x86/boot/bzImage is ready  (#17)
  ERROR: modpost: "clkdev_add" [sound/soc/mediatek/mt8195/snd-soc-mt8195-afe.ko] undefined!
  ERROR: modpost: "clkdev_drop" [sound/soc/mediatek/mt8195/snd-soc-mt8195-afe.ko] undefined!
  ERROR: modpost: "clk_unregister_gate" [sound/soc/mediatek/mt8195/snd-soc-mt8195-afe.ko] undefined!
  ERROR: modpost: "clk_register_gate" [sound/soc/mediatek/mt8195/snd-soc-mt8195-afe.ko] undefined!
  make[1]: *** [scripts/Makefile.modpost:134: modules-only.symvers] Error 1
  make[1]: *** Deleting file 'modules-only.symvers'
  make: *** [Makefile:1783: modules] Error 2

Cc: Geert Uytterhoeven <geert+renesas@glider.be>
Fixes: 940ffa194547 ("ASoC: mediatek: SND_SOC_MT8195 should depend on ARCH_MEDIATEK")
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>