NFS: Avoid using error uninitialized in nfs_lookup()
Clang warns:

fs/nfs/dir.c:1772:6: error: variable 'error' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if (fhandle == NULL || fattr == NULL)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fs/nfs/dir.c:1801:44: note: uninitialized use occurs here
        trace_nfs_lookup_exit(dir, dentry, flags, error);
                                                  ^~~~~
fs/nfs/dir.c:1772:2: note: remove the 'if' if its condition is always false
        if (fhandle == NULL || fattr == NULL)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fs/nfs/dir.c:1772:6: error: variable 'error' is used uninitialized whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
        if (fhandle == NULL || fattr == NULL)
            ^~~~~~~~~~~~~~~
fs/nfs/dir.c:1801:44: note: uninitialized use occurs here
        trace_nfs_lookup_exit(dir, dentry, flags, error);
                                                  ^~~~~
fs/nfs/dir.c:1772:6: note: remove the '||' if its condition is always false
        if (fhandle == NULL || fattr == NULL)
            ^~~~~~~~~~~~~~~~~~
fs/nfs/dir.c:1754:11: note: initialize the variable 'error' to silence this warning
        int error;
                 ^
                  = 0
2 errors generated.

Add a label to skip the call to trace_nfs_lookup_exit() when the call to
nfs_alloc_fhandle() or nfs_alloc_fattr_with_label() fails because
trace_nfs_lookup_enter() has not been called at that point so tracing
the exit does not make sense.

Fixes: 8d3df1d0387e ("NFS: Remove the label from the nfs4_lookup_res struct")
Link: https://github.com/ClangBuiltLinux/linux/issues/1498
Signed-off-by: Nathan Chancellor <nathan@kernel.org>