arm64: sve: Fix some compile errors about sve_cond_update_zcr_vq
There are some compile errors of ARM64 KVM when ARM64_SVE is not
selected, in the locations of sve_cond_update_zcr_vq used.
One error log is as following:

  CC      arch/arm64/kvm/sys_regs.o
In file included from arch/arm64/kvm/hyp/vhe/switch.c:8:0:
./arch/arm64/kvm/hyp/include/hyp/switch.h: In function ‘__hyp_sve_restore_guest’:
./arch/arm64/kvm/hyp/include/hyp/switch.h:220:2: error: implicit declaration of
function ‘sve_cond_update_zcr_vq’; did you mean
‘kvm_pmu_update_run’? [-Werror=implicit-function-declaration]
  sve_cond_update_zcr_vq(vcpu_sve_max_vq(vcpu) - 1, SYS_ZCR_EL2);
  ^~~~~~~~~~~~~~~~~~~~~~
  kvm_pmu_update_run

The root cause is that sve_cond_update_zcr_vq is not defined when
ARM64_SVE is not selected. Fix it by adding an empty definition
when CONFIG_ARM64_SVE=n.

Signed-off-by: Xiaofei Tan <tanxiaofei@huawei.com>