MIPS: traps: export a missing symbols to be able to use it from driver code
Since commit 707a4cdf86e5 ("bus: brcmstb_gisb: Allow building as module")
the brcmstb_gisb bus driver is built as a module but modpost complains once
these drivers become modules.

ERROR: modpost: "board_be_handler" [drivers/bus/brcmstb_gisb.ko] undefined!

Let's just export it.

Signed-off-by: Wang Haojun <wanghaojun@loongson.cn>
Signed-off-by: Yanteng Si <siyanteng@loongson.cn>