iwlwifi: work around reverse dependency on MEI
If the iwlmei code is a loadable module, the main iwlwifi driver
cannot be built-in:

x86_64-linux-ld: drivers/net/wireless/intel/iwlwifi/pcie/trans.o: in function `iwl_pcie_prepare_card_hw':
trans.c:(.text+0x4158): undefined reference to `iwl_mei_is_connected'

Unfortunately, Kconfig enforces the opposite, forcing the MEI driver to
not be built-in if iwlwifi is a module.

There is no easy way to express the correct dependency in Kconfig,
this is the best workaround I could come up with, turning CONFIG_IWLMEI
into a 'bool' symbol, and spelling out the exact conditions under which
it may be enabled, and then using Makefile logic to ensure it is
built-in when iwlwifi is.

A better option would be change iwl_mei_is_connected() so it could be
called from iwlwifi regardless of whether the mei driver is reachable,
but that requires a larger rework in the driver.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>