netfs: rename read_helper.c to io.c in netfs_library.rst
Fix following 'make htmldocs' error:
Error: Cannot open file ./fs/netfs/read_helper.c
WARNING: kernel-doc './scripts/kernel-doc -rst -enable-lineno
-sphinx-version 2.4.4 ./fs/netfs/read_helper.c' failed with return code 1

Fixes: ad9e5adb388f ("netfs: Rename rename read_helper.c to io.c")
Signed-off-by: Wan Jiabing <wanjiabing@vivo.com>