Documentation: futex: handle source file rename
Handle the move/rename of kernel/futex.c to kernel/futex/core.c.

Prevents docs build errors and warnings:

Error: Cannot open file ../kernel/futex.c
Error: Cannot open file ../kernel/futex.c
Error: Cannot open file ../kernel/futex.c
Error: Cannot open file ../kernel/futex.c
WARNING: kernel-doc '../scripts/kernel-doc -rst -enable-lineno -sphinx-version 1.8.5 -internal ../kernel/futex.c' failed with return code 2
WARNING: kernel-doc '../scripts/kernel-doc -rst -enable-lineno -sphinx-version 1.8.5 -internal ../kernel/futex.c' failed with return code 2

Fixes: 77e52ae35463 ("futex: Move to kernel/futex/")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Ingo Molnar <mingo@redhat.com>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Darren Hart <dvhart@infradead.org>
Cc: Davidlohr Bueso <dave@stgolabs.net>
Cc: André Almeida <andrealmeid@collabora.com>
Cc: linux-doc@vger.kernel.org
Cc: Jonathan Corbet <corbet@lwn.net>