This commit fixes the error generated due to the wrong indentation which does not follow the codding style norms set by Linux-kernel and space- bar is used in place of tab to give space which causes a visual error for some compilers
ERROR: switch and case should be at the same indent
+	switch (whence) {
+		case 1:
[...]
+		case 0:
[...]
+		default:
ERROR: code indent should use tabs where possible
+                              void (*callback)(struct dentry *))$

Signed-off-by: Aviral Gupta <shiv14112001@gmail.com>