nfilter: nf_hooks: fix build failure with NF_TABLES=n
nfnetlink_hook.c: In function 'nfnl_hook_put_nft_chain_info':
nfnetlink_hook.c:76:7: error: implicit declaration of 'nft_is_active'

This macro is only defined when NF_TABLES is enabled.
Add IS_ENABLED guards for this.

Reported-by: kernel test robot <lkp@intel.com>
Fixes: 252956528caa ("netfilter: add new hook nfnl subsystem")
Signed-off-by: Florian Westphal <fw@strlen.de>