cifs: Change cifs_ses.chans_need_reconnect and chan_index to "unsigned long"
On 32-bit (e.g. m68k):

    fs/cifs/cifssmb.c: In function ‘cifs_reconnect_tcon’:
    ./include/linux/kern_levels.h:5:18: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
    fs/cifs/cifssmb.c:201:42: note: format string is defined here
      201 |  cifs_dbg(FYI, "sess reconnect mask: 0x%lx, tcon reconnect: %d",
	  |                                        ~~^
	  |                                          |
	  |                                          long unsigned int
	  |                                        %x

    fs/cifs/transport.c: In function ‘cifs_pick_channel’:
    fs/cifs/cifsglob.h:955:20: error: passing argument 2 of ‘test_bit’ from incompatible pointer type [-Werror=incompatible-pointer-types]
      955 |  test_bit((index), &(ses)->chans_need_reconnect)
	  |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
	  |                    |
	  |                    size_t * {aka unsigned int *}
    ./arch/m68k/include/asm/bitops.h:151:66: note: expected ‘const volatile long unsigned int *’ but argument is of type ‘size_t *’ {aka ‘unsigned int *’}
      151 | static inline int test_bit(int nr, const volatile unsigned long *vaddr)
	  |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

    fs/cifs/sess.c: In function ‘cifs_chan_set_need_reconnect’:
    fs/cifs/sess.c:98:22: error: passing argument 2 of ‘bset_mem_set_bit’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       98 |  set_bit(chan_index, &ses->chans_need_reconnect);
	  |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
	  |                      |
	  |                      size_t * {aka unsigned int *}
    ./arch/m68k/include/asm/bitops.h:41:69: note: expected ‘volatile long unsigned int *’ but argument is of type ‘size_t *’ {aka ‘unsigned int *’}
       41 | static inline void bset_mem_set_bit(int nr, volatile unsigned long *vaddr)
	  |                                             ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
    fs/cifs/sess.c:98:22: error: passing argument 2 of ‘bfset_mem_set_bit’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       98 |  set_bit(chan_index, &ses->chans_need_reconnect);
	  |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
	  |                      |
	  |                      size_t * {aka unsigned int *}
    ./arch/m68k/include/asm/bitops.h:50:70: note: expected ‘volatile long unsigned int *’ but argument is of type ‘size_t *’ {aka ‘unsigned int *’}
       50 | static inline void bfset_mem_set_bit(int nr, volatile unsigned long *vaddr)
	  |                                              ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

   [...]

As bitops can only operate on long objects, and
cifs_ses_get_chan_index() already returns "unsigned long", fix this by
changing cifs_ses.chans_need_reconnect and chan_index from "size_t" to
"unsigned long".

Fixes: 374c6c7bba3cbaa1 ("cifs: changes to support multichannel during channel reconnect")
Reported-by: noreply@ellerman.id.au
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>