rtc: x86: amd-pmc: fix build failure with CONFIG_RTC_SYSTOHC=n
The newly added logic to set the RTC during suspend from
platform specific code fails with a link error here:

drivers/platform/x86/amd-pmc.c:428:30: error: use of undeclared identifier 'CONFIG_RTC_SYSTOHC_DEVICE'

Add an #ifdef so this is only done if the functionality
is enabled.

Fixes: 59348401ebed ("platform/x86: amd-pmc: Add special handling for timer based S0i3 wakeup")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>