pinctrl: mediatek: fix build error without CONFIG_PINCTRL_MTK
If CONFIG_PINCTRL_MT8365 is set without CONFIG_PINCTRL_MTK,
following build errors will be triggered:

aarch64-linux-gnu-ld: drivers/pinctrl/mediatek/pinctrl-mt8365.o: in function `mtk_pinctrl_probe':
pinctrl-mt8365.c:(.text+0x20): undefined reference to `mtk_pctrl_init'
aarch64-linux-gnu-ld: drivers/pinctrl/mediatek/pinctrl-mt8365.o: in function `mt8365_spec_pull_set':
pinctrl-mt8365.c:(.text+0x64): undefined reference to `mtk_pctrl_spec_pull_set_samereg'
aarch64-linux-gnu-ld: drivers/pinctrl/mediatek/pinctrl-mt8365.o: in function `mt8365_ies_smt_set':
pinctrl-mt8365.c:(.text+0xbc): undefined reference to `mtk_pconf_spec_set_ies_smt_range'
aarch64-linux-gnu-ld: pinctrl-mt8365.c:(.text+0xf0): undefined reference to `mtk_pconf_spec_set_ies_smt_range'
aarch64-linux-gnu-ld: drivers/pinctrl/mediatek/pinctrl-mt8365.o:(.data+0xa0): undefined reference to `mtk_eint_pm_ops'

Fix it by adding the dependency that CONFIG_PINCTRL_MT8365 will be
relied on CONFIG_PINCTRL_MTK.

Signed-off-by: Yu Kuai <yukuai3@huawei.com>