fix vmwgfx compilation error due to a missing include
This patch fixes vmwgfx driver compilation error due to a missing include

drivers/gpu/drm/vmwgfx/vmwgfx_drv.c: In function ‘vmw_vram_manager_init’:
drivers/gpu/drm/vmwgfx/vmwgfx_drv.c:678:8: error: implicit declaration of function ‘ttm_range_man_init’ [-Werror=implicit-function-declaration]
  678 |  ret = ttm_range_man_init(&dev_priv->bdev, TTM_PL_VRAM, false,
      |        ^~~~~~~~~~~~~~~~~~
drivers/gpu/drm/vmwgfx/vmwgfx_drv.c: In function ‘vmw_vram_manager_fini’:
drivers/gpu/drm/vmwgfx/vmwgfx_drv.c:690:2: error: implicit declaration of function ‘ttm_range_man_fini’ [-Werror=implicit-function-declaration]
  690 |  ttm_range_man_fini(&dev_priv->bdev, TTM_PL_VRAM);
      |  ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

Signed-off-by: Tong Zhang <ztong0001@gmail.com>