kasan: fix build for CONFIG_KASAN_HW_TAGS
When CONFIG_KASAN_HW_TAGS is selected, <linux/kasan.h> uses _RET_IP_,
but doesn't explicitly include <linux/kernel.h> where this is defined.

We used to get this via a transitive include, but since commit:

  f39650de687e3576 ("kernel.h: split out panic and oops helpers")

... this is no longer the case, and so we get a build failure:

|   CC      arch/arm64/mm/kasan_init.o
| In file included from arch/arm64/mm/kasan_init.c:10:
| ./include/linux/kasan.h: In function 'kasan_slab_free':
| ./include/linux/kasan.h:211:39: error: '_RET_IP_' undeclared (first use in this function)
|   211 |   return __kasan_slab_free(s, object, _RET_IP_, init);
|       |                                       ^~~~~~~~
| ./include/linux/kasan.h:211:39: note: each undeclared identifier is reported only once for each function it appears in
| ./include/linux/kasan.h: In function 'kasan_kfree_large':
| ./include/linux/kasan.h:219:28: error: '_RET_IP_' undeclared (first use in this function)
|   219 |   __kasan_kfree_large(ptr, _RET_IP_);
|       |                            ^~~~~~~~
| ./include/linux/kasan.h: In function 'kasan_slab_free_mempool':
| ./include/linux/kasan.h:226:34: error: '_RET_IP_' undeclared (first use in this function)
|   226 |   __kasan_slab_free_mempool(ptr, _RET_IP_);
|       |                                  ^~~~~~~~
| ./include/linux/kasan.h: In function 'kasan_check_byte':
| ./include/linux/kasan.h:277:35: error: '_RET_IP_' undeclared (first use in this function)
|   277 |   return __kasan_check_byte(addr, _RET_IP_);
|       |                                   ^~~~~~~~

Fix this by including <linux/kernel.h> explicitly.

Fixes: 6028bf777417 ("kernel.h: split out panic and oops helpers")
Signed-off-by: Mark Rutland <mark.rutland@arm.com>
Cc: Alexander Potapenko <glider@google.com>
Cc: Andrew Morton <akpm@linux-foundation.org>
Cc: Andrey Konovalov <andreyknvl@gmail.com>
Cc: Andrey Ryabinin <ryabinin.a.a@gmail.com>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Cc: Dmitry Vyukov <dvyukov@google.com>
Cc: Will Deacon <will@kernel.org>