tools: compiler-gcc.h::Keep compatible with non-clang compilers.
When HOSTC = gcc (GCC) 4.8.5, there is an error occurring as follows:
error: Undefined __has_attribute.

This problem is introduced by commit d0ee23f9d78be ("tools:
compiler-gcc.h: Guard error attribute use with __has_attribute").

To solve it, this patch is given to keep the comatibility.

Reported-by: Zeal Robot <zealci@zte.com.cn>
Co-developed-by: wangyong <wang.yong12@zte.com.cn>
Signed-off-by: xu xin <xu.xin16@zte.com.cn>