arm: patch: FUNCTION_GRAPH_TRACER depends on CPU_ENDIAN_BE8 or !CPU_ENDIAN_BE32
If CONFIG_FUNCTION_GRAPH_TRACER=y, the following errors will be seen
while compiling patch.c

arch/arm/kernel/patch.c: In function ‘__patch_text_real’:
arch/arm/kernel/patch.c:94:11: error: implicit declaration of function
‘__opcode_to_mem_thumb32’; did you mean ‘__opcode_to_mem_thumb16’?
[-Werror=implicit-function-declaration]
    insn = __opcode_to_mem_thumb32(insn);
           ^~~~~~~~~~~~~~~~~~~~~~~
           __opcode_to_mem_thumb16

Signed-off-by: Zhang Jianhua <zhangjianhua18@huawei.com>