platform: dell: all DELL_WMI driver options depend on DELL_WMI
A randconfig or a user can set/enable DELL_WMI_PRIVACY even when
DELL_WMI is not enabled. This leads to a build error in
dell-laptop.o:

ld: drivers/platform/x86/dell/dell-laptop.o: in function `dell_init':
dell-laptop.c:(.init.text+0x719): undefined reference to `dell_privacy_has_mic_mute'

Fix this by enclosing the DELL_WMI driver options inside a
if DELL_WMI / endif bracket.

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Perry Yuan <Perry.Yuan@dell.com>
Cc: Dell.Client.Kernel@dell.com
Cc: platform-driver-x86@vger.kernel.org
Cc: Hans de Goede <hdegoede@redhat.com>
Cc: Mark Gross <mgross@linux.intel.com>