cpufreq: qcom-cpufreq-hw: Fix 'make allmodconfig' build, part 2
Commit 86afc1df661a adds a reference to a symbol that doesn't have an
EXPORT_PER_CPU_SYMBOL, which fails if qcom-cpufreq-hw is built as a module.

ERROR: modpost: "cpu_scale" [drivers/cpufreq/qcom-cpufreq-hw.ko] undefined!

Thanks to Seonjae Park for pointing me in the right direction.

Fixes: 86afc1df661a ("cpufreq: qcom-cpufreq-hw: Add dcvs interrupt support")
Suggested-by: SeongJae Park <sjpark@amazon.de>
Signed-off-by: Valdis Kletnieks <valdis.kletnieks@vt.edu>