smpboot: remove duplicate inline keyword
'static inline void __always_inline' is one more 'inline' than needed,
and it's in the wrong place as gcc points out when extra warnings
are enabled:

kernel/smpboot.c:50:1: error: 'inline' is not at beginning of declaration [-Werror=old-style-declaration]
   50 | static inline void __always_inline idle_init(unsigned int cpu)

Move it to the right place instead.

Fixes: e9ba16e68cce ("smpboot: Mark idle_init() as __always_inlined to work around aggressive compiler un-inlining")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>