ASoC: samsung: midas_wm1811: Fix build error when CONFIG_GPIOLIB is not set
Fix build error when CONFIG_GPIOLIB is not set:

sound/soc/samsung/midas_wm1811.c: In function 'midas_fm_set':
sound/soc/samsung/midas_wm1811.c:205:3: error:
 implicit declaration of function 'gpiod_set_value_cansleep';
 did you mean 'gpio_set_value_cansleep'? [-Werror=implicit-function-declaration]
  205 |   gpiod_set_value_cansleep(priv->gpio_fm_sel, 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
      |   gpio_set_value_cansleep
sound/soc/samsung/midas_wm1811.c: In function 'midas_probe':
sound/soc/samsung/midas_wm1811.c:445:22: error:
 implicit declaration of function 'devm_gpiod_get_optional';
 did you mean 'devm_clk_get_optional'? [-Werror=implicit-function-declaration]
  445 |  priv->gpio_fm_sel = devm_gpiod_get_optional(dev, "fm-sel", GPIOD_OUT_HIGH);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
      |                      devm_clk_get_optional
sound/soc/samsung/midas_wm1811.c:445:61:
 error: 'GPIOD_OUT_HIGH' undeclared (first use in this function);
 did you mean 'GPIOF_INIT_HIGH'?
  445 |  priv->gpio_fm_sel = devm_gpiod_get_optional(dev, "fm-sel", GPIOD_OUT_HIGH);
      |                                                             ^~~~~~~~~~~~~~
      |                                                             GPIOF_INIT_HIGH

Fixes: fd0ea9cd9698 ("ASoC: samsung: Add sound support for Midas boards")
Reported-by: Hulk Robot <hulkci@huawei.com>
Signed-off-by: Wei Yongjun <weiyongjun1@huawei.com>