arm64: export this_cpu_has_cap
It's now used in a coresight driver that can be a loadable module:

ERROR: modpost: "this_cpu_has_cap" [drivers/hwtracing/coresight/coresight-trbe.ko] undefined!

Fixes: 8a1065127d95 ("coresight: trbe: Add infrastructure for Errata handling")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>