checkpatch: Don't show signatures in git-log
I have git-log setup to show signatures.  I've recently noticed this
breaking checkpatch error messages, which show something like

    ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit gpg: Signatu (":05 PM PDT")'
    #8:
    the module region by 3a02764c372c ("riscv: Ensure BPF_JIT_REGION_START

instead of something more helpful, like

    ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 3a02764c372c ("riscv: Ensure BPF_JIT_REGION_START aligned with PMD size")'
    #8:
    the module region by 3a02764c372c ("riscv: Ensure BPF_JIT_REGION_START

which shows up with this patch.  I'm not sure if these just started
showing up for if I just noticed them or if they've been around forever.

I've only found it necessary to add --no-show-signature to the git-log
invocation in git_commit_info(), but a cursory glance indicates that the
other two invocations may suffer from similar problems so I've just
added it everywhere.

Signed-off-by: Palmer Dabbelt <palmerdabbelt@google.com>