block: include dd_queued{,_show} into proper BLK_DEBUG_FS guard
This commit fixes a compilation issue to an unused function if
BLK_DEBUG_FS setting is not enabled. This usually happens in tiny
kernels with several debug options disabled. For further details,
see the message below:

../block/mq-deadline.c:274:12: error: ‘dd_queued’ defined but not used [-Werror=unused-function]
  274 | static u32 dd_queued(struct deadline_data *dd, enum dd_prio prio)
      |            ^~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Julio Faracco <jfaracco@redhat.com>