selftests: Fix vm_handle_exception undefined error
Compile setftests on x86_64 occurs following error:
make -C tools/testing/selftests
...

x86_64/hyperv_features.c:618:2: warning: implicit declaration of function ‘vm_handle_exception’ [-Wimplicit-function-declaration]
  618 |  vm_handle_exception(vm, GP_VECTOR, guest_gp_handler);
/usr/bin/ld: /tmp/cclOnpml.o: in function `main':
tools/testing/selftests/kvm/x86_64/hyperv_features.c:618: undefined reference to `vm_handle_exception'
collect2: error: ld returned 1 exit status

The reason is that commit b78f4a596692 ("KVM: selftests: Rename vm_handle_exception")
renamed "vm_handle_exception" function to "vm_install_exception_handler" function.

Fix it by replacing "vm_handle_exception" with "vm_install_exception_handler"
in corresponding selftests files.

Signed-off-by: Chen Lifu <chenlifu@huawei.com>