iio: frequency: adrf6780: Fix adrf6780_spi_{read,write}()
Clang warns:

drivers/iio/frequency/adrf6780.c:117:1: error: all paths through this
function will call itself [-Werror,-Winfinite-recursion]
{
^
drivers/iio/frequency/adrf6780.c:138:1: error: all paths through this
function will call itself [-Werror,-Winfinite-recursion]
{
^
2 errors generated.

The underscore variants should be used here.

Fixes: 63aaf6d06d87 ("iio: frequency: adrf6780: add support for ADRF6780")
Link: https://github.com/ClangBuiltLinux/linux/issues/1490
Signed-off-by: Nathan Chancellor <nathan@kernel.org>