regulator: lp872x: fix enum conversion warning
clang warns that the argument to devm_gpiod_get_optional()
is the wrong type:

drivers/regulator/lp872x.c:689:57: error: implicit conversion from enumeration type 'enum lp872x_dvs_state' to different enumeration type 'enum gpiod_flags' [-Werror,-Wenum-conversion]
        dvs->gpio = devm_gpiod_get_optional(lp->dev, "ti,dvs", pinstate);
                    ~~~~~~~~~~~~~~~~~~~~~~~                    ^~~~~~~~

The enum value is specifcally chosen to be the same here, but
the compiler only sees the mismatched types. This could be
worked around using another ?: expression, but it seems easiest
to replace the assignment with a macro.

Fixes: 72bf80cf09c4 ("regulator: lp872x: replacing legacy gpio interface for gpiod")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>