linux-next: Tree for Oct 5 (warnings: a. trace; b. mm/migrate)
On 10/6/21 9:39 AM, Randy Dunlap wrote:
>>>> ../mm/migrate.c:3216:22: error: 'migrate_on_reclaim_callback' defined
>>>> but not used [-Werror=unused-function]
>>>>   static int __meminit migrate_on_reclaim_callback(struct
>>>> notifier_block
>>>> *self,
>>>>                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>>>> ../mm/migrate.c:3197:13: error: 'set_migration_target_nodes' defined
>>>> but
>>>> not used [-Werror=unused-function]
>>>>   static void set_migration_target_nodes(void)
>>>>               ^~~~~~~~~~~~~~~~~~~~~~~~~~
>>>>
>>>>
>>>> (example usage to get the randconfig files:
>>>> KCONFIG_SEED=0xBFBEA13C make [ARCH=x86_64] randconfig
>>>> )

Randy, thanks for the .config!  That did the trick.

Andrew, attached is a replacement patch for

	mm-migrate-add-cpu-hotplug-to-demotion-ifdef.patch

I could do an incremental as well if that would be easier.  But, the fix
here required a bit of a change of tactics from the original and
necessitated a rewrite of the changelog.

Subject: [PATCH] mm/migrate: separate CPU and memory hotplug notifiers
Date: Wed, 6 Oct 2021 11:08:46 -0700
Message-ID: <20211006180846.3321352-1-dave.hansen@intel.com>
X-Mailer: git-send-email 2.25.1
In-Reply-To: <20210924161255.E5FE8F7E@davehans-spike.ostc.intel.com>
References: <20210924161255.E5FE8F7E@davehans-spike.ostc.intel.com>

From: Dave Hansen <dave.hansen@linux.intel.com>

Once upon a time, the node demotion updates were driven solely by memory
hotplug events.  But now, there are handlers for both CPU and memory
hotplug.

However, the #ifdef around the code checks only memory hotplug.  A system
that has HOTPLUG_CPU=y but MEMORY_HOTPLUG=n would miss CPU hotplug events.

Update the #ifdef around the common code.  Add memory and CPU-specific
option are off.  Move some CPU-hotplug-specific functions to reside under
their specific #ifdef.

Link: https://lkml.kernel.org/r/20210924161255.E5FE8F7E@davehans-spike.ostc.intel.com
Fixes: 884a6e5d1f93 ("mm/migrate: update node demotion order on hotplug events")
Signed-off-by: Dave Hansen <dave.hansen@linux.intel.com>
Cc: "Huang, Ying" <ying.huang@intel.com>
Cc: Michal Hocko <mhocko@suse.com>
Cc: Wei Xu <weixugc@google.com>
Cc: Oscar Salvador <osalvador@suse.de>
Cc: David Rientjes <rientjes@google.com>
Cc: Dan Williams <dan.j.williams@intel.com>
Cc: David Hildenbrand <david@redhat.com>
Cc: Greg Thelen <gthelen@google.com>
Cc: Yang Shi <yang.shi@linux.alibaba.com>
Cc: Randy Dunlap <rdunlap@infradead.org>