drm/vmwgfx: fix size_t format string
On architectures with size_t different from 'unsigned long', gcc
prints this warning:

drivers/gpu/drm/vmwgfx/vmwgfx_gem.c: In function 'vmw_bo_print_info':
drivers/gpu/drm/vmwgfx/vmwgfx_gem.c:230:40: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
  230 |         seq_printf(m, "\t\t0x%08x: %12ld bytes %s, type = %s",
      |                                    ~~~~^
      |                                        |
      |                                        long int
      |                                    %12d
  231 |                    id, bo->base.base.size, placement, type);
      |                        ~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     size_t {aka unsigned int}

Use the correct %zd modifier.

Fixes: 8afa13a0583f ("drm/vmwgfx: Implement DRIVER_GEM")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>