uapi: fix asm/shmbuf.h userspace compilation errors
Userspace cannot compile <asm/shmbuf.h> due to some missing type
definitions.  For example, compiling it for x86_64 fails with the
following diagnostics:

  HDRTEST usr/include/asm/shmbuf.h
In file included from ./usr/include/asm/shmbuf.h:6,
                 from <command-line>:
./usr/include/asm-generic/shmbuf.h:26:33: error: field 'shm_perm' has incomplete type
   26 |         struct ipc64_perm       shm_perm;       /* operation perms */
      |                                 ^~~~~~~~
./usr/include/asm-generic/shmbuf.h:27:9: error: unknown type name 'size_t'
   27 |         size_t                  shm_segsz;      /* size of segment (bytes) */
      |         ^~~~~~
./usr/include/asm-generic/shmbuf.h:40:9: error: unknown type name '__kernel_pid_t'
   40 |         __kernel_pid_t          shm_cpid;       /* pid of creator */
      |         ^~~~~~~~~~~~~~
./usr/include/asm-generic/shmbuf.h:41:9: error: unknown type name '__kernel_pid_t'
   41 |         __kernel_pid_t          shm_lpid;       /* pid of last operator */
      |         ^~~~~~~~~~~~~~

Replace size_t with __kernel_size_t and include <asm/ipcbuf.h> to make
asm/shmbuf.h self-contained, also add it to the compile-test coverage.

Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>