s390: add <linux/minmax.h> to <asm/facility.h>
S390's <asm/facility.h> uses the min_t() macro, so it should
include <linux/minmax.h> to avoid build errors.

In file included from arch/s390/pci/pci_insn.c:12:
arch/s390/include/asm/facility.h: In function '__stfle':
arch/s390/include/asm/facility.h:98:22: error: implicit declaration of
function 'min_t' [-Werror=implicit-function-declaration]
   98 |                 nr = min_t(unsigned long, (nr + 1) * 8, size * 8);
arch/s390/include/asm/facility.h:98:28: error: expected expression
before 'unsigned'
   98 |                 nr = min_t(unsigned long, (nr + 1) * 8, size * 8);

Fixes: 4f18d869ffd0 ("s390: fix stfle zero padding")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
Cc: Naresh Kamboju <naresh.kamboju@linaro.org>
Cc: Heiko Carstens <hca@linux.ibm.com>
Cc: Vasily Gorbik <gor@linux.ibm.com>
Cc: Christian Borntraeger <borntraeger@de.ibm.com>
Cc: linux-s390@vger.kernel.org