parisc: stacktrace: add <linux/kernel.h> to prevent build error
stacktrace.c uses __kernel_text_address() so it needs to
include <linux/kernel.h>.  Otherwise there is a build error:

arch/parisc/kernel/stacktrace.c: In function 'walk_stackframe':
arch/parisc/kernel/stacktrace.c:25:21: error: implicit declaration of
function '__kernel_text_address'
[-Werror=implicit-function-declaration]
   25 |                 if (__kernel_text_address(info.ip))

Fixes: aeb1e833a4c3 ("parisc: Switch to ARCH_STACKWALK implementation")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
Cc: Naresh Kamboju <naresh.kamboju@linaro.org>
Cc: "James E.J. Bottomley" <James.Bottomley@HansenPartnership.com>
Cc: Helge Deller <deller@gmx.de>
Cc: linux-parisc@vger.kernel.org