net: phy: dp83640: Drop unused PAGE0 define
parisc:allmodconfig fails to build with the following error.

In file included from drivers/net/phy/dp83640.c:23:
drivers/net/phy/dp83640_reg.h:8: error: "PAGE0" redefined

The dp83640 driver does not use this define, so just remove it.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>