iwlwifi: iwlmvm: add rfkill dependency
IWLMVM uses symbol rfkill_soft_blocked, thus RFKILL should be a
dependency

In file included from drivers/net/wireless/intel/iwlwifi/mvm/fw.c:19:
drivers/net/wireless/intel/iwlwifi/mvm/mvm.h: In function ‘iwl_mvm_mei_set_sw_rfkill_state’:
drivers/net/wireless/intel/iwlwifi/mvm/mvm.h:2215:24: error: implicit declaration of function ‘rfkill_soft_blocked’; did you mean ‘rfkill_blocked’? [-Werror=implicit-function-declaration]
 2215 |   mvm->hw_registered ? rfkill_soft_blocked(mvm->hw->wiphy->rfkill) : false;
      |                        ^~~~~~~~~~~~~~~~~~~
      |                        rfkill_blocked
cc1: some warnings being treated as errors

Signed-off-by: Tong Zhang <ztong0001@gmail.com>