nl80211: use correct enum type in reg_reload_regdb
NL80211_USER_REG_HINT_USER is not something that can be
assigned to an 'enum nl80211_reg_initiator', as pointed out
by gcc.

net/wireless/reg.c: In function 'reg_reload_regdb':
net/wireless/reg.c:1137:28: error: implicit conversion from 'enum nl80211_user_reg_hint_type' to 'enum nl80211_reg_initiator' [-Werror=enum-conversion]

I don't know what was intended here, most likely it was either
NL80211_REGDOM_SET_BY_CORE (same numeric value) or
NL80211_REGDOM_SET_BY_USER (most similar name), so I pick the former
here, leaving the behavior unchanged while avoiding the warning.

Fixes: 1eda919126b4 ("nl80211: reset regdom when reloading regdb")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>