fat: Use pointer to d_name[0] in put_user() for compat case
The put_user(val,ptr) macro wants a pointer in the second parameter, but in
fat_ioctl_filldir() the d_name field references a whole "array of chars".
Usually the compiler automatically converts it and uses a pointer to that
array, but it's more clean to explicitly give the real pointer to where someting
is put, which is in this case the first character of the d_name[] array.

I noticed that issue while trying to optimize the parisc put_user() macro
and used an intermediate variable to store the pointer. In that case I
got this error:

In file included from include/linux/uaccess.h:11,
                 from include/linux/compat.h:17,
                 from fs/fat/dir.c:18:
fs/fat/dir.c: In function ‘fat_ioctl_filldir’:
fs/fat/dir.c:725:33: error: invalid initializer
  725 |                 if (put_user(0, d2->d_name)                     ||         \
      |                                 ^~
include/asm/uaccess.h:152:33: note: in definition of macro ‘__put_user’
  152 |         __typeof__(ptr) __ptr = ptr;                            \
      |                                 ^~~
fs/fat/dir.c:759:1: note: in expansion of macro ‘FAT_IOCTL_FILLDIR_FUNC’
  759 | FAT_IOCTL_FILLDIR_FUNC(fat_ioctl_filldir, __fat_dirent)

The patch below cleans it up.

Signed-off-by: Helge Deller <deller@gmx.de>