cifs: Fix build error when no CONFIG_DNS_RESOLVER
hulk robot following build error:
  ld: fs/cifs/dns_resolve.o: in function `dns_resolve_server_name_to_ip':
  dns_resolve.c:(.text+0x154): undefined reference to `dns_query'
  make: *** [Makefile:1251: vmlinux] Error 1

Fixes: e488292a31fa ("cifs: On cifs_reconnect, resolve the hostname again.")
Reported-by: Hulk Robot <hulkci@huawei.com>
Signed-off-by: Zhang Xiaoxu <zhangxiaoxu5@huawei.com>