pwm: ep93xx: Fix uninitialized variable bug in ep93xx_pwm_apply()
Smatch found a potential uninitialized variable in ep93xx_pwm_apply():

    drivers/pwm/pwm-ep93xx.c:147 ep93xx_pwm_apply()
    error: uninitialized symbol 'ret'.

Initialize "ret" to zero at the start to solve this issue.

Fixes: f6ef94edf0f6 ("pwm: ep93xx: Unfold legacy callbacks into ep93xx_pwm_apply()")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>