drm: vmwgfx: add header file for ttm_range_manager
Add a header file for ttm_range_manager function prototypes to
eliminate build errors:

../drivers/gpu/drm/vmwgfx/vmwgfx_drv.c: In function ‘vmw_vram_manager_init’:
../drivers/gpu/drm/vmwgfx/vmwgfx_drv.c:678:8: error: implicit declaration of function ‘ttm_range_man_init’; did you mean ‘ttm_tt_mgr_init’? [-Werror=implicit-function-declaration]
  ret = ttm_range_man_init(&dev_priv->bdev, TTM_PL_VRAM, false,
../drivers/gpu/drm/vmwgfx/vmwgfx_drv.c: In function ‘vmw_vram_manager_fini’:
../drivers/gpu/drm/vmwgfx/vmwgfx_drv.c:690:2: error: implicit declaration of function ‘ttm_range_man_fini’; did you mean ‘ttm_pool_mgr_fini’? [-Werror=implicit-function-declaration]
  ttm_range_man_fini(&dev_priv->bdev, TTM_PL_VRAM);

Fixes: 9c3006a4cc1b ("drm/ttm: remove available_caching")
Fixes: a343160235f5 ("drm/vmwgfx/ttm: fix the non-THP cleanup path.")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: "VMware Graphics" <linux-graphics-maintainer@vmware.com>
Cc: Roland Scheidegger <sroland@vmware.com>
Cc: Zack Rusin <zackr@vmware.com>
Cc: dri-devel@lists.freedesktop.org
Cc: Dave Airlie <airlied@redhat.com>
Cc: Christian König <christian.koenig@amd.com>