sign-file: Use OpenSSL provided define to compile out missing (deprecated) APIs
OpenSSL's ENGINE API is deprecated in OpenSSL v3.0.

Use OPENSSL_NO_ENGINE to ensure the ENGINE API is only used if it is
present.  This will safeguard against compile errors when using SSL
implementations which lack support for this deprecated API.

>>> referenced by sign-file.c
>>>               /tmp/sign-file-370a2f.o:(main)

error: undefined symbol: ENGINE_init
>>> referenced by sign-file.c
>>>               /tmp/sign-file-370a2f.o:(main)

ld.lld: error: undefined symbol: ENGINE_ctrl_cmd_string
>>> referenced by sign-file.c
>>>               /tmp/sign-file-370a2f.o:(main)

ld.lld: error: undefined symbol: ENGINE_load_private_key
>>> referenced by sign-file.c
>>>               /tmp/sign-file-370a2f.o:(main)
  HDRINST usr/include/linux/virtio_i2c.h
make[1]: *** [/src/kernel/scripts/Makefile.host:95: scripts/sign-file] Error 1

Cc: David Howells <dhowells@redhat.com>
Cc: David Woodhouse <dwmw2@infradead.org>
Cc: Eric Biggers <ebiggers@kernel.org>
Cc: keyrings@vger.kernel.org
Co-developed-by: Adam Langley <agl@google.com>
Signed-off-by: Lee Jones <lee.jones@linaro.org>