net/mlx5i: avoid unused function warning for mlx5i_flow_type_mask
Without CONFIG_MLX5_EN_RXNFC, the function is unused, breaking the
build with CONFIG_WERROR:

mlx5/core/ipoib/ethtool.c:36:12: error: unused function 'mlx5i_flow_type_mask' [-Werror,-Wunused-function]
static u32 mlx5i_flow_type_mask(u32 flow_type)

We could add another #ifdef or mark this function inline, but
replacing the existing #ifdef with a __maybe_unused seems best
because that improves build coverage and avoids introducing
similar problems the next time this code changes.

Fixes: 9fbe1c25ecca ("net/mlx5i: Enable Rx steering for IPoIB via ethtool")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>