PM: AVS: qcom-cpr: select CONFIG_NVMEM
nvmem_cell_read_variable_le_u32 is only defined when CONFIG_NVMEM
is set, otherwise we end up with this build failure:

drivers/soc/qcom/cpr.c: In function 'cpr_populate_ring_osc_idx':
drivers/soc/qcom/cpr.c:814:23: error: implicit declaration of function 'nvmem_cell_read_variable_le_u32' [-Werror=implicit-function-declaration]
  814 |                 ret = nvmem_cell_read_variable_le_u32(drv->dev, fuses->ring_osc, &data);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Select the framwork from Kconfig.

Fixes: 6feba6a62c57 ("PM: AVS: qcom-cpr: Use nvmem_cell_read_variable_le_u32()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>