net: ethernet: ti: fix netdev_queue compiling error
There is a compiling error in am65-cpsw-nuss.c while not selecting
CONFIG_BQL:

drivers/net/ethernet/ti/am65-cpsw-nuss.c: In function
‘am65_cpsw_nuss_ndo_host_tx_timeout’:
drivers/net/ethernet/ti/am65-cpsw-nuss.c:353:26: error:
‘struct netdev_queue’ has no member named ‘dql’
  353 |      dql_avail(&netif_txq->dql),
      |                          ^~

This problem is solved by adding the #ifdef CONFIG_BQL directive
where struct dql is used.

Fixes: 93a76530316a ("net: ethernet: ti: introduce am65x/j721e gigabit eth subsystem driver")
Signed-off-by: Chen Jiahao <chenjiahao16@huawei.com>