mm/mapping_dirty_helpers: Guard hugepage pud's usage
Mapping dirty helpers have, so far, been only used on X86, but
a port of vmwgfx to ARM64 exposed a problem which results
in a compilation error on ARM64 systems:
mm/mapping_dirty_helpers.c: In function ‘wp_clean_pud_entry’:
mm/mapping_dirty_helpers.c:172:32: error: implicit declaration of function ‘pud_dirty’; did you mean ‘pmd_dirty’? [-Werror=implicit-function-declaration]

This is due to the fact that mapping_dirty_helpers code assumes
that pud_dirty is always defined, which is not the case for
architectures that don't define CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD.

ARM64 arch is a little inconsistent when it comes to PUD
hugepage helpers, e.g. it defines pud_young but not pud_dirty
but regardless of that the core kernel code shouldn't assume
that any of the PUD hugepage helpers are available unless
CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD is defined. This
prevents compilation errors whenever one of the drivers
is ported to new architectures.

Signed-off-by: Zack Rusin <zackr@vmware.com>
Cc: Andrew Morton <akpm@linux-foundation.org>
Cc: Thomas Hellström (Intel) <thomas_os@shipmail.org>
Cc: linux-mm@kvack.org
Cc: linux-kernel@vger.kernel.org