regulator: BD71815: select REGULATOR_ROHM to fix link errors
With REGULATOR_ROHM there are linker errors:

ld: drivers/regulator/bd71815-regulator.o: in function `set_hw_dvs_levels':
bd71815-regulator.c:(.text+0xbb): undefined reference to `rohm_regulator_set_dvs_levels'
ld: drivers/regulator/bd71815-regulator.o: in function `buck12_set_hw_dvs_levels':
bd71815-regulator.c:(.text+0x33e): undefined reference to `rohm_regulator_set_dvs_levels'

Fixes: 1aad39001e851 ("regulator: Support ROHM BD71815 regulators")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Matti Vaittinen <matti.vaittinen@fi.rohmeurope.com>
Cc: Lee Jones <lee.jones@linaro.org>
Cc: Liam Girdwood <lgirdwood@gmail.com>
Cc: Mark Brown <broonie@kernel.org>