io_uring: fix uninitialized return
The clang build fails with this error
io_uring.c:9396:9: error: variable 'ret' is uninitialized when used here
        return ret;
               ^~~~
Return 0 directly.

Fixes: b77e315a9644 ("io_uring: avoid ring quiesce while registering/unregistering eventfd")
Signed-off-by: Tom Rix <trix@redhat.com>