regulator: bd71815: select CONFIG_ROHM_REGULATOR
The newly added driver is missing a dependency as shown by this
randconfig build failure:

arm-linux-gnueabi-ld: drivers/regulator/bd71815-regulator.o: in function `buck12_set_hw_dvs_levels':
bd71815-regulator.c:(.text+0x4b6): undefined reference to `rohm_regulator_set_dvs_levels'

Fixes: 1aad39001e85 ("regulator: Support ROHM BD71815 regulators")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>