net: switchdev: switchdev_handle_fdb_del_to_device(): fix no-op function for disabled CONFIG_NET_SWITCHDEV
In patch 8ca07176ab00 ("net: switchdev: introduce a fanout helper for
SWITCHDEV_FDB_{ADD,DEL}_TO_DEVICE") new functionality including static
inline no-op functions if CONFIG_NET_SWITCHDEV is disabled was added.

This patch fixes the following build error for disabled
CONFIG_NET_SWITCHDEV:

| In file included from include/net/dsa.h:23,
|                  from net/core/flow_dissector.c:8:
| include/net/switchdev.h:410:1: error: expected identifier or ‘(’ before ‘{’ token
|   410 | {
|       | ^
| include/net/switchdev.h:399:1: warning: ‘switchdev_handle_fdb_del_to_device’ declared ‘static’ but never defined [-Wunused-function]
|   399 | switchdev_handle_fdb_del_to_device(struct net_device *dev,
|       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 8ca07176ab00 ("net: switchdev: introduce a fanout helper for SWITCHDEV_FDB_{ADD,DEL}_TO_DEVICE")
Cc: Vladimir Oltean <vladimir.oltean@nxp.com>
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>