firmware: tegra: Fix build error while ARCH_TEGRA_234_SOC enabled
drivers/firmware/tegra/bpmp.c:861:51:
 error: ‘tegra186_soc’ undeclared here (not in a function); did you mean ‘tegra_ivc’?
  { .compatible = "nvidia,tegra186-bpmp", .data = &tegra186_soc },
                                                   ^~~~~~~~~~~~
                                                   tegra_ivc

Fixes: 0ebdf11699d0 ("firmware: tegra: Enable BPMP support on Tegra234")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>