udf: shut up pointer cast warning
On 32-bit architectures, the workaround of storing the directory position
in the private_data pointer causes a warning, as loff_t does not fit in
a pointer:

fs/udf/dir.c: In function 'udf_readdir':
fs/udf/dir.c:78:25: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   78 |         if (ctx->pos != (uintptr_t)file->private_data) {
      |                         ^
fs/udf/dir.c:211:30: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  211 |         file->private_data = (void *)(uintptr_t)ctx->pos;
      |                              ^

An extra cast to uintptr_t shuts up the warning. This is of course
still broken if the position is ever beyond the first 2^32 bytes (4GB).

I have not found a clear information on whether directories this
large are allowed on UDF, but it seems unlikely.

Fixes: 39a464de961f ("udf: Fix crash after seekdir")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>