tools/virtio: Miscellaneous build fixes
 - Fix pthread LDFLAGS in Makefile: use -pthread compile and link switch as
   per man-page; the current -lpthread emits a number of undefined refs:

virtio_ring.o: In function `spin_lock':
tools/virtio/./linux/spinlock.h:16: undefined reference to `pthread_spin_lock'
virtio_ring.o: In function `spin_unlock':
tools/virtio/./linux/spinlock.h:22: undefined reference to `pthread_spin_unlock'
virtio_ring.o: In function `spin_lock':
tools/virtio/./linux/spinlock.h:16: undefined reference to `pthread_spin_lock'
virtio_ring.o: In function `spin_unlock':
tools/virtio/./linux/spinlock.h:22: undefined reference to `pthread_spin_unlock'
virtio_ring.o: In function `spin_lock':
tools/virtio/./linux/spinlock.h:16: undefined reference to `pthread_spin_lock'
virtio_ring.o: In function `spin_unlock':
tools/virtio/./linux/spinlock.h:22: undefined reference to `pthread_spin_unlock'
virtio_ring.o: In function `spin_lock':
tools/virtio/./linux/spinlock.h:16: undefined reference to `pthread_spin_lock'
virtio_ring.o: In function `spin_unlock':
tools/virtio/./linux/spinlock.h:22: undefined reference to `pthread_spin_unlock'

 - Missing drv_to_virtio definition and related includes: a copy of uio.h
   with a helper, using a struct folio reference, removed.

 - Added empty mm_types.h

 - Added mocked moduleparam() definitions.

 - Fixed virtio_test and vringh_test initialization to allow drv_to_virtio
   inline to work properly when invoked from tets code.

Signed-off-by: Cristian Marussi <cristian.marussi@arm.com>