HID: prodikeys: add USB_HID dependency
Like with the other drivers that recently got fixed, this one
fails to link if USB_HID is disabled or unreachable:

ERROR: modpost: "usb_hid_driver" [drivers/hid/hid-prodikeys.ko] undefined!

Fixes: f237d9028f84 ("HID: add USB_HID dependancy on some USB HID drivers")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>