ASoC: SOF: Intel: move CODEC_PROBE_RETRIES definition
The macro is defined in an #ifdef but used outside:

sound/soc/sof/intel/hda-codec.c: In function 'hda_codec_probe':
sound/soc/sof/intel/hda-codec.c:132:42: error: 'CODEC_PROBE_RETRIES' undeclared (first use in this function)
  132 |         } while (resp == -1 && retry++ < CODEC_PROBE_RETRIES);
      |                                          ^~~~~~~~~~~~~~~~~~~

Move it to a place where it can be seen unconditionally.

Fixes: 046aede2f847 ("ASoC: SOF: Intel: Retry codec probing if it fails")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>