pcmcia: Guard yenta_dev_{resume,suspend}_noirq() on CONFIG_PM_SLEEP
When building without CONFIG_PM_SLEEP:

drivers/pcmcia/yenta_socket.c:1322:12: error: ‘yenta_dev_resume_noirq’ defined but not used [-Werror=unused-function]
 1322 | static int yenta_dev_resume_noirq(struct device *dev)
      |            ^~~~~~~~~~~~~~~~~~~~~~
drivers/pcmcia/yenta_socket.c:1303:12: error: ‘yenta_dev_suspend_noirq’ defined but not used [-Werror=unused-function]
 1303 | static int yenta_dev_suspend_noirq(struct device *dev)
      |            ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

SET_NOIRQ_SYSTEM_SLEEP_PM_OPS evaluates to an empty macro when
CONFIG_PM_SLEEP is not set. Every callback in yenta_pm_ops depends on
CONFIG_PM_SLEEP to work properly so just guard this whole block on
CONFIG_PM_SLEEP, rather than CONFIG_PM, which CONFIG_PM_SLEEP will
select.

Fixes: 3daaf2c7aae8 ("pcmcia: Make use of the helper macro SET_NOIRQ_SYSTEM_SLEEP_PM_OPS()")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>