mfd: simple-mfd-i2c: Fix linker error due to new mfd-core dependency
Select CONFIG_MFD_CORE from CONFIG_MFD_SIMPLE_MFD_I2C, now that
simple-mfd-i2c.c calls devm_mfd_add_devices(), to fix the following
linker error:

 ld: drivers/mfd/simple-mfd-i2c.o: in function `simple_mfd_i2c_probe':
 simple-mfd-i2c.c:(.text+0x62): undefined reference to `devm_mfd_add_devices'
 make: *** [Makefile:1187: vmlinux] Error 1

Fixes: c753ea31781a ("mfd: simple-mfd-i2c: Add support for registering devices via MFD cells")
Cc: stable@vger.kernel.org # 5.15.x
Signed-off-by: Tyler Hicks <tyhicks@linux.microsoft.com>