mm: split out anon_vma declarations to separate header
The patch to add anonymous vma names causes a build failure in
some configurations:

include/linux/mm_types.h: In function 'is_same_vma_anon_name':
include/linux/mm_types.h:924:37: error: implicit declaration of function 'strcmp' [-Werror=implicit-function-declaration]
  924 |         return name && vma_name && !strcmp(name, vma_name);
      |                                     ^~~~~~
include/linux/mm_types.h:22:1: note: 'strcmp' is defined in header '<string.h>'; did you forget to '#include <string.h>'?

This should not really be part of linux/mm_types.h in the first
place, as that header is meant to only contain structure defintions
and need a minimum set of indirect includes itself. While the
header clearly includes more than it should at this point, let's
not make it worse by including string.h as well, which would
pull in the expensive (compile-speed wise) fortify-string logic.

Move the new functions to a separate header that is only included
where necessary to avoid bloating linux/mm_types.h further.

Fixes: 52f545eb6dd7 ("mm: add a field to store names for private anonymous memory")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>