ASoC: amd: vangogh: add SPI dependency
Without CONFIG_SPI, this fails to build:

WARNING: unmet direct dependencies detected for SND_SOC_CS35L41_SPI
  Depends on [n]: SOUND [=m] && !UML && SND [=m] && SND_SOC [=m] && SPI_MASTER [=n]
  Selected by [m]:
  - SND_SOC_AMD_VANGOGH_MACH [=m] && SOUND [=m] && !UML && SND [=m] && SND_SOC [=m] && SND_SOC_AMD_ACP5x [=m] && I2C [=y]
ERROR: modpost: "spi_setup" [sound/soc/codecs/snd-soc-cs35l41-spi.ko] undefined!
ERROR: modpost: "__devm_regmap_init_spi" [sound/soc/codecs/snd-soc-cs35l41-spi.ko] undefined!

Fixes: 96792fdd77cd ("ASoC: amd: enable vangogh platform machine driver build")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>