trace_osnoise: rename main to trace_main to avoid Werror=main
kernel builds with -Werror=main, gcc report failed.

Avoids warnings like:
kernel/trace/trace_osnoise.c:1515:8: error: ‘main’ is usually a function [-Werror=main]

Fixes: a955d7eac177 ("trace: Add timerlat tracer")
Cc: Steven Rostedt <rostedt@goodmis.org>
Cc: Ingo Molnar <mingo@redhat.com>
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>