clk: renesas: cpg-mssr: fix R-Car S4-8 link failure
Without CONFIG_CLK_RCAR_GEN4_CPG, this driver fails to link:

x86_64-linux-ld: drivers/clk/renesas/r8a779a0-cpg-mssr.o:(.init.rodata+0x70): undefined reference to `rcar_gen4_cpg_clk_register'

Fixes: 95d3d41f958f ("clk: renesas: cpg-mssr: Add support for R-Car S4-8")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>