drm: i915: fix build when ACPI is disabled and BACKLIGHT=m
When CONFIG_DRM_I915=y, CONFIG_ACPI is not set, and
CONFIG_BACKLIGHT_CLASS_DEVICE=m, not due to I915 config,
there are build errors trying to reference backlight_device_{un}register().

Changing the use of IS_ENABLED() to IS_REACHABLE() in intel_panel.[ch]
fixes this.

ld: drivers/gpu/drm/i915/display/intel_panel.o: in function `intel_backlight_device_register':
intel_panel.c:(.text+0x2ec1): undefined reference to `backlight_device_register'
ld: drivers/gpu/drm/i915/display/intel_panel.o: in function `intel_backlight_device_unregister':
intel_panel.c:(.text+0x2f93): undefined reference to `backlight_device_unregister'

ld: drivers/gpu/drm/i915/display/intel_panel.o: in function `intel_backlight_device_register':
intel_panel.c:(.text+0x2ec1): undefined reference to `backlight_device_register'
ld: drivers/gpu/drm/i915/display/intel_panel.o: in function `intel_backlight_device_unregister':
intel_panel.c:(.text+0x2f93): undefined reference to `backlight_device_unregister'

Fixes: 912e8b12eedb ("drm/i915: register backlight device also when backlight class is a module")
Fixes: 44c1220a441c ("drm/i915: extract intel_panel.h from intel_drv.h")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Ville Syrjälä <ville.syrjala@linux.intel.com>
Cc: Jani Nikula <jani.nikula@intel.com>
Cc: Damien Lespiau <damien.lespiau@intel.com>
Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
Cc: Jani Nikula <jani.nikula@linux.intel.com>
Cc: Joonas Lahtinen <joonas.lahtinen@linux.intel.com>
Cc: Rodrigo Vivi <rodrigo.vivi@intel.com>
Cc: intel-gfx@lists.freedesktop.org
Cc: dri-devel@lists.freedesktop.org