usb: musb: davinci: change the variable type
vbus_state is define as bool but on davinci.c assigning a value
'-1' to the bool variable.

Fix the following coccicheck error:

drivers/usb/musb//davinci.c:532:2-18:
ERROR: Assignment of non-0/1 constant to bool variable

By changing the variable type to int.
As vbus_state need more three values/states more required by
vbus_state variable.

 /* 0/1 vs "-1 == unknown/init" */

Signed-off-by: Saurav Girepunje <saurav.girepunje@google.com>