net: phy: at803x: fix at803x_match_phy_id mismatch
There are two conflicting patches in net-next, one removed
the at803x_get_features() function and the other added another
user:

drivers/net/phy/at803x.c: In function 'at803x_get_features':
drivers/net/phy/at803x.c:706:14: error: implicit declaration of function 'at803x_match_phy_id' [-Werror=implicit-function-declaration]

Change the new caller over to an open-coded comparison as well.

Fixes: 8887ca5474bd ("net: phy: at803x: simplify custom phy id matching")
Fixes: b856150c8098 ("net: phy: at803x: mask 1000 Base-X link mode")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>