libperf: Fix 32-bit build for tests uint64_t printf
Commit a7f3713f6bf2 ("libperf tests: Add test_stat_multiplexing test")
added printf's of 64-bit ints using %lu which doesn't work on 32-bit
builds:

tests/test-evlist.c:529:29: error: format ‘%lu’ expects argument of type \
  ‘long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]

Use PRIu64 instead which works on both 32-bit and 64-bit systems.

Fixes: a7f3713f6bf2 ("libperf tests: Add test_stat_multiplexing test")
Cc: Shunsuke Nakamura <nakamura.shun@fujitsu.com>
Signed-off-by: Rob Herring <robh@kernel.org>