thermal: int340x: processor_thermal: Fix build error
drivers/thermal/intel/int340x_thermal/processor_thermal_mbox.c: In function ‘send_mbox_cmd’:
drivers/thermal/intel/int340x_thermal/processor_thermal_mbox.c:79:16:
 error: implicit declaration of function ‘readq’; did you mean ‘readl’? [-Werror=implicit-function-declaration]
    *cmd_resp = readq((void __iomem *) (proc_priv->mmio_base + MBOX_OFFSET_DATA));
                ^~~~~
                readl

Add missing include to fix this.

Fixes: aeb58c860dc5 ("thermal/drivers/int340x: processor_thermal: Suppot 64 bit RFIM responses")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>