media: atomisp: fix `-Werror=return-type`
Bedirhan reported build error:
```
  drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.c: In function ‘input_system_configure_channel_sensor’:
  drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.c:1649:1: error: control reaches end of non-void function [-Werror=return-type]
   1649 | }
        | ^
  cc1: some warnings being treated as errors
  make[4]: *** [scripts/Makefile.build:277: drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.o] Error 1
  make[3]: *** [scripts/Makefile.build:540: drivers/staging/media/atomisp] Error 2
  make[2]: *** [scripts/Makefile.build:540: drivers/staging/media] Error 2
  make[1]: *** [scripts/Makefile.build:540: drivers/staging] Error 2
  make: *** [Makefile:1868: drivers] Error 2
```

Commit 264f590899146baa19e0ab5689e55fadbc292333 ("media: atomisp:
remove useless returns") incorrectly removed a required return results
in the above build error. Reinstate it.

Cc: Pavel Skripkin <paskripkin@gmail.com>
Cc: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
Cc: Sakari Ailus <sakari.ailus@linux.intel.com>
Cc: linux-media@vger.kernel.org
Cc: linux-staging@lists.linux.dev
Cc: linux-kernel@vger.kernel.org
Reported-by: Bedirhan KURT <windowz414@gnuweeb.org>
Fixes: 264f590899146baa19e0ab5689e55fadbc292333 ("media: atomisp: remove useless returns")
Signed-off-by: Ammar Faizi <ammar.faizi@students.amikom.ac.id>