ipv6: add spaces for accept_ra_min_hop_limit
The checkpatch reported
ERROR: spaces required around that '=' (ctx:VxW)
from the net/ipv6/addrconf.c.

So, spaces are added for accept_ra_min_hop_limit.

Signed-off-by: Jiwon Kim <jiwonaid0@gmail.com>