drm: rcar-du: crtc: force depends on cmm
After the patch 78b6bb1d24db ("drm: rcar-du: crtc: Control CMM operations"),
the cmm module must be included in the crtc. We cannot remove this
configuration option separately. Therefore, simply linking them together
is the best solution, otherwise some errors will be reported.

 rcar_du_crtc.c:(.text+0x194): undefined reference to `rcar_cmm_setup'
 rcar_du_crtc.c:(.text+0x11bc): undefined reference to `rcar_cmm_enable'
 rcar_du_crtc.c:(.text+0x1604): undefined reference to `rcar_cmm_disable'
 rcar_du_kms.c:(.text+0x768): undefined reference to `rcar_cmm_init'

Fixes: 78b6bb1d24db ("rm: rcar-du: crtc: Control CMM operations")
Reported-by: kernel-bot <k2ci@kylinos.cn>
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>