tools/runqslower: Change state to __state
The task_struct state got renamed to __state, causing
compile fail:

  runqslower.bpf.c:77:12: error: no member named 'state' in 'struct task_struct'
        if (prev->state == TASK_RUNNING)

As this is tracing prog, I think we don't need to use
READ_ONCE to access __state.

Fixes: 2f064a59a11f ("sched: Change task_struct::state")
Signed-off-by: Jiri Olsa <jolsa@kernel.org>