clk: hisilicon: hi3559A: select CONFIG_RESET_HISI
The reset functions are in a library that has to be selected
for each driver using them:

aarch64-linux-ld: drivers/clk/hisilicon/clk-hi3559a.o: in function `hi3559av100_crg_remove':
clk-hi3559a.c:(.text+0x1c8): undefined reference to `hisi_reset_exit'
clk-hi3559a.c:(.text+0x1c8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hisi_reset_exit'
aarch64-linux-ld: drivers/clk/hisilicon/clk-hi3559a.o: in function `hi3559av100_crg_probe':
clk-hi3559a.c:(.text+0x284): undefined reference to `hisi_reset_init'
clk-hi3559a.c:(.text+0x284): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hisi_reset_init'
aarch64-linux-ld: clk-hi3559a.c:(.text+0x2e8): undefined reference to `hisi_reset_exit'
clk-hi3559a.c:(.text+0x2e8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `hisi_reset_exit'

Add the select to 3559 as well.

Fixes: 6c81966107dc ("clk: hisilicon: Add clock driver for hi3559A SoC")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>